## Summary
Gradient Boosting is an algorithm derived from Decision Tree algorithm, it performs sequential construction of multiple Decision Trees and conducts learning
# Issue
- I haven't understood the specific purpose of the algorithm yet.
- I can't use the lightgbm library on my jupyter notebook even though I have it installed on my machine( But I can use visual code) . I tried to fix it but still can not

## Library import
- numpy
- lightgbm
- skearn

In [1]:
import numpy as np
import lightgbm as lgb
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn import metrics

## Data set Iris

In [5]:
iris = datasets.load_iris()
X, y = iris.data, iris.target
print("X: ", X)
print("y: ", y)

X:  [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.

**Data train and data test**

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y)

## Build model (C1)

In [ ]:
lgb_train = lgb.Dataset(X_train, y_train)
lgb_eval  = lgb.Dataset(X_test, y_test, reference=lgb_train)

*Setting parameters for LightGBM*

In [7]:
lgbm_params = {
    'objective': 'multiclass', #Multi-class classification problem
    'num_class': 3, #Number of Class in this problem is 3
}

*Pass parameters to Model and train model*

In [ ]:
model = lgb.train(lgbm_params, lgb_train, valid_sets=lgb_eval)

*Predictions for the Test dataset*

In [ ]:
y_pred = model.predict(X_test, num_iteration=model.best_iteration)
y_pred_max = np.argmax(y_pred, axis=1)

## Build model (C2)
### Use interface sklearn

*Declare model*

In [ ]:
model = lgb.LGBMClassifier()

*Train model*

In [ ]:
model.fit(X_train, y_train)

*Predictions for the Test dataset*

In [ ]:
y_pred = model.predict_proba(X_test)
y_pred_max = np.argmax(y_pred, axis=1) 

## Review model

In [ ]:
accuracy = metrics.accuracy_score(y_test, y_pred_max)
print(accuracy)